version: '3.7'

services:
  database:
    image: postgres
    container_name: code-test.postgres
    env_file:
      - .env
    networks:
      - adminer
      - code-test-db
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    container_name: code-test.adminer
    ports:
      - 3308:8080
    links:
      - database
    networks:
      - adminer

networks:
  code-test-db: ~
  adminer: ~
