version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    container_name: coding-test.api
    env_file:
      - .env
    depends_on:
      - database
    networks:
      backend: ~
    ports:
      - "${APP_PORT}:${APP_PORT}"

  database:
    image: postgres
    container_name: coding-test.postgres
    env_file:
      - .env
    networks:
      backend: ~
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/docker-containers/coding-test/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: coding-test.adminer
    ports:
      - 3308:8080
    links:
      - database
    networks:
      backend: ~

networks:
  backend: ~
