version: '3.7'

services:
  database:
    image: postgres
    container_name: coding-test.postgres
    env_file:
      - .env
    networks:
      - adminer
      - coding-test-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
    - ~/docker-containers/coding-test/postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: coding-test.adminer
    ports:
      - 3308:8080
    links:
      - database
    networks:
      - adminer

networks:
  coding-test-db: ~
  adminer: ~
